package com.example.util

import android.content.Context
import android.content.Intent
import android.graphics.Canvas
import android.graphics.Color
import android.graphics.Paint
import android.graphics.pdf.PdfDocument
import androidx.core.content.FileProvider
import com.example.data.model.DiagnosisResult
import java.io.File
import java.io.FileOutputStream

object PdfExporter {

    fun exportAndShareDiagnosisPdf(context: Context, diagnosis: DiagnosisResult) {
        try {
            val pdfDocument = PdfDocument()
            val pageInfo = PdfDocument.PageInfo.Builder(595, 842, 1).create() // A4 size
            val page = pdfDocument.startPage(pageInfo)
            val canvas: Canvas = page.canvas

            val titlePaint = Paint().apply {
                color = Color.parseColor("#1B4D2E")
                textSize = 22f
                isFakeBoldText = true
            }

            val subtitlePaint = Paint().apply {
                color = Color.parseColor("#2E7D32")
                textSize = 14f
                isFakeBoldText = true
            }

            val textPaint = Paint().apply {
                color = Color.DKGRAY
                textSize = 12f
            }

            var y = 50f

            canvas.drawText("AI PLANT DOCTOR - DIAGNOSIS REPORT", 40f, y, titlePaint)
            y += 30f

            canvas.drawText("Date: ${diagnosis.dateFormatted}", 40f, y, textPaint)
            y += 20f
            canvas.drawText("Location: ${diagnosis.location}", 40f, y, textPaint)
            y += 30f

            canvas.drawText("PLANT IDENTIFICATION", 40f, y, subtitlePaint)
            y += 20f
            canvas.drawText("Plant Name: ${diagnosis.plantName} (${diagnosis.scientificName})", 40f, y, textPaint)
            y += 18f
            canvas.drawText("Confidence: ${diagnosis.confidence}% | Health Score: ${diagnosis.healthScore}%", 40f, y, textPaint)
            y += 30f

            canvas.drawText("DIAGNOSIS & CONDITION", 40f, y, subtitlePaint)
            y += 20f
            canvas.drawText("Detected Issue: ${diagnosis.diseaseName}", 40f, y, textPaint)
            y += 18f
            canvas.drawText("Severity: ${diagnosis.diseaseSeverity} | Risk Level: ${diagnosis.riskLevel}", 40f, y, textPaint)
            y += 18f
            canvas.drawText("Nutrient Status: ${diagnosis.nutrientStatus}", 40f, y, textPaint)
            y += 30f

            canvas.drawText("TREATMENT & RECOMMENDATIONS", 40f, y, subtitlePaint)
            y += 20f
            canvas.drawText("Organic Treatment: ${diagnosis.organicFertilizer}", 40f, y, textPaint)
            y += 18f
            canvas.drawText("Organic Pesticide: ${diagnosis.organicPesticide}", 40f, y, textPaint)
            y += 18f
            canvas.drawText("Chemical Treatment: ${diagnosis.chemicalFertilizer}", 40f, y, textPaint)
            y += 18f
            canvas.drawText("Pruning Guide: ${diagnosis.pruningRecommendation}", 40f, y, textPaint)
            y += 30f

            canvas.drawText("CARE REQUIREMENTS", 40f, y, subtitlePaint)
            y += 20f
            canvas.drawText("Watering: ${diagnosis.waterStatus} | Sunlight: ${diagnosis.sunlightRequirement}", 40f, y, textPaint)
            y += 18f
            canvas.drawText("Temp: ${diagnosis.temperatureRequirement} | Humidity: ${diagnosis.humidityRequirement}", 40f, y, textPaint)
            y += 40f

            canvas.drawText("Generated by AI Plant Doctor Mobile App", 40f, y, textPaint)

            pdfDocument.finishPage(page)

            val pdfDir = File(context.cacheDir, "reports")
            if (!pdfDir.exists()) pdfDir.mkdirs()
            val pdfFile = File(pdfDir, "Diagnosis_${diagnosis.plantName}_${diagnosis.id}.pdf")
            pdfDocument.writeTo(FileOutputStream(pdfFile))
            pdfDocument.close()

            val uri = FileProvider.getUriForFile(
                context,
                "${context.packageName}.fileprovider",
                pdfFile
            )

            val shareIntent = Intent(Intent.ACTION_SEND).apply {
                type = "application/pdf"
                putExtra(Intent.EXTRA_STREAM, uri)
                putExtra(Intent.EXTRA_SUBJECT, "AI Plant Doctor Report - ${diagnosis.plantName}")
                addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION)
            }
            context.startActivity(Intent.createChooser(shareIntent, "Share Plant Report PDF"))

        } catch (e: Exception) {
            e.printStackTrace()
        }
    }
}
